global:
  scrape_interval: 5s # Scrape often for this demo (default is usually 1m)

scrape_configs:
  - job_name: 'rate-limiter'
    static_configs:
      - targets: 
        # Inside Docker network, we use the service names
        - 'limiter-1:2112'
        - 'limiter-2:2112'